export interface NewReleases {
  album_type: string;
  artists?: (ArtistsEntity)[] | null;
  available_markets?: (string)[] | null;
  external_urls: ExternalUrls;
  href: string;
  id: string;
  images?: (ImagesEntity)[] | null;
  name: string;
  release_date: string;
  release_date_precision: string;
  total_tracks: number;
  type: string;
  uri: string;
}
export interface ArtistsEntity {
  external_urls: ExternalUrls;
  href: string;
  id: string;
  name: string;
  type: string;
  uri: string;
}
export interface ExternalUrls {
  spotify: string;
}
export interface ImagesEntity {
  height: number;
  url: string;
  width: number;
}

export const staticNewReleases: Array<NewReleases> = [
  {
      "album_type": "album",
      "artists": [
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/56oDRnqbIiwx4mymNEv7dS"
              },
              "href": "https://api.spotify.com/v1/artists/56oDRnqbIiwx4mymNEv7dS",
              "id": "56oDRnqbIiwx4mymNEv7dS",
              "name": "Lizzo",
              "type": "artist",
              "uri": "spotify:artist:56oDRnqbIiwx4mymNEv7dS"
          }
      ],
      "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
      ],
      "external_urls": {
          "spotify": "https://open.spotify.com/album/1NgFBv1PxMG1zhFDW1OrRr"
      },
      "href": "https://api.spotify.com/v1/albums/1NgFBv1PxMG1zhFDW1OrRr",
      "id": "1NgFBv1PxMG1zhFDW1OrRr",
      "images": [
          {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b2730bb0fe89076743883482769a",
              "width": 640
          },
          {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e020bb0fe89076743883482769a",
              "width": 300
          },
          {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d000048510bb0fe89076743883482769a",
              "width": 64
          }
      ],
      "name": "Special",
      "release_date": "2022-07-15",
      "release_date_precision": "day",
      "total_tracks": 12,
      "type": "album",
      "uri": "spotify:album:1NgFBv1PxMG1zhFDW1OrRr"
  },
  {
      "album_type": "album",
      "artists": [
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/57vWImR43h4CaDao012Ofp"
              },
              "href": "https://api.spotify.com/v1/artists/57vWImR43h4CaDao012Ofp",
              "id": "57vWImR43h4CaDao012Ofp",
              "name": "Steve Lacy",
              "type": "artist",
              "uri": "spotify:artist:57vWImR43h4CaDao012Ofp"
          }
      ],
      "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
      ],
      "external_urls": {
          "spotify": "https://open.spotify.com/album/3Ks0eeH0GWpY4AU20D5HPD"
      },
      "href": "https://api.spotify.com/v1/albums/3Ks0eeH0GWpY4AU20D5HPD",
      "id": "3Ks0eeH0GWpY4AU20D5HPD",
      "images": [
          {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b27368968350c2550e36d96344ee",
              "width": 640
          },
          {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e0268968350c2550e36d96344ee",
              "width": 300
          },
          {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d0000485168968350c2550e36d96344ee",
              "width": 64
          }
      ],
      "name": "Gemini Rights",
      "release_date": "2022-07-15",
      "release_date_precision": "day",
      "total_tracks": 10,
      "type": "album",
      "uri": "spotify:album:3Ks0eeH0GWpY4AU20D5HPD"
  },
  {
      "album_type": "album",
      "artists": [
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/6Ha4aES39QiVjR0L2lwuwq"
              },
              "href": "https://api.spotify.com/v1/artists/6Ha4aES39QiVjR0L2lwuwq",
              "id": "6Ha4aES39QiVjR0L2lwuwq",
              "name": "Yo Gotti",
              "type": "artist",
              "uri": "spotify:artist:6Ha4aES39QiVjR0L2lwuwq"
          },
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/3tJoFztHeIJkJWMrx0td2f"
              },
              "href": "https://api.spotify.com/v1/artists/3tJoFztHeIJkJWMrx0td2f",
              "id": "3tJoFztHeIJkJWMrx0td2f",
              "name": "Moneybagg Yo",
              "type": "artist",
              "uri": "spotify:artist:3tJoFztHeIJkJWMrx0td2f"
          },
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/3rO1KMi81CCLjSjkImNtrA"
              },
              "href": "https://api.spotify.com/v1/artists/3rO1KMi81CCLjSjkImNtrA",
              "id": "3rO1KMi81CCLjSjkImNtrA",
              "name": "CMG The Label",
              "type": "artist",
              "uri": "spotify:artist:3rO1KMi81CCLjSjkImNtrA"
          }
      ],
      "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
      ],
      "external_urls": {
          "spotify": "https://open.spotify.com/album/0mX7631qrFwwcnuRzuPpWU"
      },
      "href": "https://api.spotify.com/v1/albums/0mX7631qrFwwcnuRzuPpWU",
      "id": "0mX7631qrFwwcnuRzuPpWU",
      "images": [
          {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273d3484108146959cb1835f601",
              "width": 640
          },
          {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02d3484108146959cb1835f601",
              "width": 300
          },
          {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851d3484108146959cb1835f601",
              "width": 64
          }
      ],
      "name": "Gangsta Art",
      "release_date": "2022-07-15",
      "release_date_precision": "day",
      "total_tracks": 27,
      "type": "album",
      "uri": "spotify:album:0mX7631qrFwwcnuRzuPpWU"
  },
  {
      "album_type": "album",
      "artists": [
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/35l9BRT7MXmM8bv2WDQiyB"
              },
              "href": "https://api.spotify.com/v1/artists/35l9BRT7MXmM8bv2WDQiyB",
              "id": "35l9BRT7MXmM8bv2WDQiyB",
              "name": "beabadoobee",
              "type": "artist",
              "uri": "spotify:artist:35l9BRT7MXmM8bv2WDQiyB"
          }
      ],
      "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
      ],
      "external_urls": {
          "spotify": "https://open.spotify.com/album/2rhNQbqRNxiNQkDXTffe1V"
      },
      "href": "https://api.spotify.com/v1/albums/2rhNQbqRNxiNQkDXTffe1V",
      "id": "2rhNQbqRNxiNQkDXTffe1V",
      "images": [
          {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273384d10f967c2b914de7e2713",
              "width": 640
          },
          {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02384d10f967c2b914de7e2713",
              "width": 300
          },
          {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851384d10f967c2b914de7e2713",
              "width": 64
          }
      ],
      "name": "Beatopia",
      "release_date": "2022-07-15",
      "release_date_precision": "day",
      "total_tracks": 14,
      "type": "album",
      "uri": "spotify:album:2rhNQbqRNxiNQkDXTffe1V"
  },
  {
      "album_type": "single",
      "artists": [
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/40ZNYROS4zLfyyBSs2PGe2"
              },
              "href": "https://api.spotify.com/v1/artists/40ZNYROS4zLfyyBSs2PGe2",
              "id": "40ZNYROS4zLfyyBSs2PGe2",
              "name": "Zach Bryan",
              "type": "artist",
              "uri": "spotify:artist:40ZNYROS4zLfyyBSs2PGe2"
          }
      ],
      "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
      ],
      "external_urls": {
          "spotify": "https://open.spotify.com/album/2qPki6xBkJ1Mbra43t7hnA"
      },
      "href": "https://api.spotify.com/v1/albums/2qPki6xBkJ1Mbra43t7hnA",
      "id": "2qPki6xBkJ1Mbra43t7hnA",
      "images": [
          {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b27340efbcb2e827ba3dd58426ed",
              "width": 640
          },
          {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e0240efbcb2e827ba3dd58426ed",
              "width": 300
          },
          {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d0000485140efbcb2e827ba3dd58426ed",
              "width": 64
          }
      ],
      "name": "Summertime Blues",
      "release_date": "2022-07-15",
      "release_date_precision": "day",
      "total_tracks": 9,
      "type": "album",
      "uri": "spotify:album:2qPki6xBkJ1Mbra43t7hnA"
  },
  {
      "album_type": "single",
      "artists": [
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/3MdXrJWsbVzdn6fe5JYkSQ"
              },
              "href": "https://api.spotify.com/v1/artists/3MdXrJWsbVzdn6fe5JYkSQ",
              "id": "3MdXrJWsbVzdn6fe5JYkSQ",
              "name": "Latto",
              "type": "artist",
              "uri": "spotify:artist:3MdXrJWsbVzdn6fe5JYkSQ"
          }
      ],
      "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
      ],
      "external_urls": {
          "spotify": "https://open.spotify.com/album/2RJKx64TCTSA1rbwh3C3ib"
      },
      "href": "https://api.spotify.com/v1/albums/2RJKx64TCTSA1rbwh3C3ib",
      "id": "2RJKx64TCTSA1rbwh3C3ib",
      "images": [
          {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b27367a9eb460c0159eac70cc9ed",
              "width": 640
          },
          {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e0267a9eb460c0159eac70cc9ed",
              "width": 300
          },
          {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d0000485167a9eb460c0159eac70cc9ed",
              "width": 64
          }
      ],
      "name": "PUSSY",
      "release_date": "2022-07-15",
      "release_date_precision": "day",
      "total_tracks": 1,
      "type": "album",
      "uri": "spotify:album:2RJKx64TCTSA1rbwh3C3ib"
  },
  {
      "album_type": "single",
      "artists": [
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/3dz0NnIZhtKKeXZxLOxCam"
              },
              "href": "https://api.spotify.com/v1/artists/3dz0NnIZhtKKeXZxLOxCam",
              "id": "3dz0NnIZhtKKeXZxLOxCam",
              "name": "Porter Robinson",
              "type": "artist",
              "uri": "spotify:artist:3dz0NnIZhtKKeXZxLOxCam"
          },
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/47mIJdHORyRerp4os813jD"
              },
              "href": "https://api.spotify.com/v1/artists/47mIJdHORyRerp4os813jD",
              "id": "47mIJdHORyRerp4os813jD",
              "name": "League of Legends",
              "type": "artist",
              "uri": "spotify:artist:47mIJdHORyRerp4os813jD"
          }
      ],
      "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
      ],
      "external_urls": {
          "spotify": "https://open.spotify.com/album/0j4PaZDmzAJ4PlS89zcHbW"
      },
      "href": "https://api.spotify.com/v1/albums/0j4PaZDmzAJ4PlS89zcHbW",
      "id": "0j4PaZDmzAJ4PlS89zcHbW",
      "images": [
          {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b2732b1a62237771427afb899387",
              "width": 640
          },
          {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e022b1a62237771427afb899387",
              "width": 300
          },
          {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d000048512b1a62237771427afb899387",
              "width": 64
          }
      ],
      "name": "Everything Goes On",
      "release_date": "2022-07-14",
      "release_date_precision": "day",
      "total_tracks": 1,
      "type": "album",
      "uri": "spotify:album:0j4PaZDmzAJ4PlS89zcHbW"
  },
  {
      "album_type": "single",
      "artists": [
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/7CajNmpbOovFoOoasH2HaY"
              },
              "href": "https://api.spotify.com/v1/artists/7CajNmpbOovFoOoasH2HaY",
              "id": "7CajNmpbOovFoOoasH2HaY",
              "name": "Calvin Harris",
              "type": "artist",
              "uri": "spotify:artist:7CajNmpbOovFoOoasH2HaY"
          },
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/31TPClRtHm23RisEBtV3X7"
              },
              "href": "https://api.spotify.com/v1/artists/31TPClRtHm23RisEBtV3X7",
              "id": "31TPClRtHm23RisEBtV3X7",
              "name": "Justin Timberlake",
              "type": "artist",
              "uri": "spotify:artist:31TPClRtHm23RisEBtV3X7"
          },
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/26VFTg2z8YR0cCuwLzESi2"
              },
              "href": "https://api.spotify.com/v1/artists/26VFTg2z8YR0cCuwLzESi2",
              "id": "26VFTg2z8YR0cCuwLzESi2",
              "name": "Halsey",
              "type": "artist",
              "uri": "spotify:artist:26VFTg2z8YR0cCuwLzESi2"
          }
      ],
      "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
      ],
      "external_urls": {
          "spotify": "https://open.spotify.com/album/62SWIKrov7HPXU0Jpc6LY1"
      },
      "href": "https://api.spotify.com/v1/albums/62SWIKrov7HPXU0Jpc6LY1",
      "id": "62SWIKrov7HPXU0Jpc6LY1",
      "images": [
          {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b2739b93a80dbfd3d789065d7b67",
              "width": 640
          },
          {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e029b93a80dbfd3d789065d7b67",
              "width": 300
          },
          {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d000048519b93a80dbfd3d789065d7b67",
              "width": 64
          }
      ],
      "name": "Stay With Me (with Justin Timberlake, Halsey, & Pharrell)",
      "release_date": "2022-07-15",
      "release_date_precision": "day",
      "total_tracks": 1,
      "type": "album",
      "uri": "spotify:album:62SWIKrov7HPXU0Jpc6LY1"
  },
  {
      "album_type": "album",
      "artists": [
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/74KM79TiuVKeVCqs8QtB0B"
              },
              "href": "https://api.spotify.com/v1/artists/74KM79TiuVKeVCqs8QtB0B",
              "id": "74KM79TiuVKeVCqs8QtB0B",
              "name": "Sabrina Carpenter",
              "type": "artist",
              "uri": "spotify:artist:74KM79TiuVKeVCqs8QtB0B"
          }
      ],
      "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
      ],
      "external_urls": {
          "spotify": "https://open.spotify.com/album/5kDmlA2g9Y1YCbNo2Ufxlz"
      },
      "href": "https://api.spotify.com/v1/albums/5kDmlA2g9Y1YCbNo2Ufxlz",
      "id": "5kDmlA2g9Y1YCbNo2Ufxlz",
      "images": [
          {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273700f7bf79c9f063ad0362bdf",
              "width": 640
          },
          {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02700f7bf79c9f063ad0362bdf",
              "width": 300
          },
          {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851700f7bf79c9f063ad0362bdf",
              "width": 64
          }
      ],
      "name": "emails i can't send",
      "release_date": "2022-07-15",
      "release_date_precision": "day",
      "total_tracks": 13,
      "type": "album",
      "uri": "spotify:album:5kDmlA2g9Y1YCbNo2Ufxlz"
  },
  {
      "album_type": "album",
      "artists": [
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/2Kv0ApBohrL213X9avMrEn"
              },
              "href": "https://api.spotify.com/v1/artists/2Kv0ApBohrL213X9avMrEn",
              "id": "2Kv0ApBohrL213X9avMrEn",
              "name": "Lil Silva",
              "type": "artist",
              "uri": "spotify:artist:2Kv0ApBohrL213X9avMrEn"
          }
      ],
      "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
      ],
      "external_urls": {
          "spotify": "https://open.spotify.com/album/4RRWbTmBBpmf43GbLEtlTR"
      },
      "href": "https://api.spotify.com/v1/albums/4RRWbTmBBpmf43GbLEtlTR",
      "id": "4RRWbTmBBpmf43GbLEtlTR",
      "images": [
          {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273dc895e6416e7f122fb4947d4",
              "width": 640
          },
          {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02dc895e6416e7f122fb4947d4",
              "width": 300
          },
          {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851dc895e6416e7f122fb4947d4",
              "width": 64
          }
      ],
      "name": "Yesterday Is Heavy",
      "release_date": "2022-07-15",
      "release_date_precision": "day",
      "total_tracks": 12,
      "type": "album",
      "uri": "spotify:album:4RRWbTmBBpmf43GbLEtlTR"
  },
  {
      "album_type": "single",
      "artists": [
          {
              "external_urls": {
                  "spotify": "https://open.spotify.com/artist/3bYcjbVAN3rAuU3TMzw2mB"
              },
              "href": "https://api.spotify.com/v1/artists/3bYcjbVAN3rAuU3TMzw2mB",
              "id": "3bYcjbVAN3rAuU3TMzw2mB",
              "name": "Marcus Mumford",
              "type": "artist",
              "uri": "spotify:artist:3bYcjbVAN3rAuU3TMzw2mB"
          }
      ],
      "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BZ",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
      ],
      "external_urls": {
          "spotify": "https://open.spotify.com/album/4GoINkOwOUS17uL017LeP6"
      },
      "href": "https://api.spotify.com/v1/albums/4GoINkOwOUS17uL017LeP6",
      "id": "4GoINkOwOUS17uL017LeP6",
      "images": [
          {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b2732323f8d172cb2fe4c95c458f",
              "width": 640
          },
          {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e022323f8d172cb2fe4c95c458f",
              "width": 300
          },
          {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d000048512323f8d172cb2fe4c95c458f",
              "width": 64
          }
      ],
      "name": "Cannibal",
      "release_date": "2022-07-14",
      "release_date_precision": "day",
      "total_tracks": 1,
      "type": "album",
      "uri": "spotify:album:4GoINkOwOUS17uL017LeP6"
  }
];